utils_sources := \
	CallStack.cpp \
	Debug.cpp \
	Flattenable.cpp \
	misc.cpp \
	RefBase.cpp \
	SharedBuffer.cpp \
	String16.cpp \
	String8.cpp \
	SystemClock.cpp \
	TextOutput.cpp \
	Timers.cpp \
	Unicode.cpp \
	VectorImpl.cpp \
	BufferedTextOutput.cpp \
	Threads.cpp \
	Static.cpp

objects += $(patsubst %.cpp,utils/%.o, $(utils_sources))
